ci: sonar test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,27 +13,42 @@ jobs:
     with:
       jdk-version: 17
       version: ${{ github.ref_name }}
-    secrets: inherit
+      sonar-skip: true
 
   QualityGate:
     runs-on: ubuntu-latest
     needs: [Build]
+    env:
+      COMMIT_SHA: ${{ github.sha }}
+      BRANCH_REF: master
+      SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
+      SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
     steps:
-      - name: Download Sonar Scan Meta Data
-        uses: actions/download-artifact@v3
-        with:
-          name: Sonar Meta Data
       - name: SonarQube Quality Gate Check
-        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
-        with:
-          scanMetadataReportFile: report-task.txt
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-      - name: "SonarCloud Quality Gate Status"
-        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
+        run: |
+          ANALYSIS_ID=$( curl --silent "${SONAR_HOST_URL}/api/project_analyses/search?project=${SONAR_PROJECT_KEY}&branch=${BRANCH_REF/\//%2F}" | jq -r "first(.analyses[]|select(.revision==\"$COMMIT_SHA\").key)")
+          
+          if [[ -z $ANALYSIS_ID ]]; then
+            echo "No Sonar Scan result found for commit $COMMIT_SHA"
+            exit 1
+          fi
+          
+          QG_STATUS=$(curl --silent "${SONAR_HOST_URL}/api/qualitygates/project_status?analysisId=${ANALYSIS_ID}" | jq -r ".projectStatus.status")
+          
+          if [[ $QG_STATUS == "OK" ]]; then
+            echo "Quality Gate passed"
+            exit 0
+          elif [[ $QG_STATUS == "ERROR" ]]; then
+            echo "Quality Gate failed"
+            exit 1
+          else
+            echo "Could not find Quality Gate information for analysis id ${ANALYSIS_ID}"
+            exit 1
+          fi
 
   DependencyScan:
     runs-on: ubuntu-latest
+    if: false
     env:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
     steps:
@@ -51,7 +66,7 @@ jobs:
         run: snyk test --maven-aggregate-project --org=$SNYK_ORG_ID
 
   Deploy:
-    needs: [Build, QualityGate, DependencyScan]
+    needs: [Build, QualityGate] #, DependencyScan]
     uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_deploy.yml@master
     with:
       version: ${{ github.ref_name }}
@@ -64,6 +79,7 @@ jobs:
   Monitor:
     runs-on: ubuntu-latest
     needs: [Deploy]
+    if: false
     env:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
     steps:
